backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog/News"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "events"
    label: "Events Calendar"
    folder: "events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Event Title", name: "title", widget: "string" }
      - { label: "Event Date & Time", name: "date", widget: "datetime" }
      - { label: "Location", name: "location", widget: "string", default: "Veterans Military Museum" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Description", name: "body", widget: "markdown" }
